"""Setup script for PyKokkos Debugger"""

import os
from pathlib import Path

from setuptools import setup

# Native debugger binaries, pinned at install time:
#
#     CUDA_GDB=/usr/local/cuda/bin/cuda-gdb pip install -e .
#
# A variable that is unset here keeps the plain tool name, resolved on $PATH
# when the debugger is launched. Written before setup() so every command
# (develop, editable_wheel, build_py, install) regenerates the module.
_DEBUGGER_DEFAULTS = {"GDB": "gdb", "CUDA_GDB": "cuda-gdb", "HIP_GDB": "rocgdb"}


def _write_debugger_paths():
    lines = ["# Generated by setup.py. Do not edit; re-run pip install to change.", ""]
    for name, default in _DEBUGGER_DEFAULTS.items():
        lines.append(f"{name} = {os.environ.get(name) or default!r}")
    Path(__file__).parent.joinpath("core", "debugger_paths.py").write_text("\n".join(lines) + "\n")


_write_debugger_paths()

setup(
    name="pkdb",
    version="0.1.0",
    author="PyKokkos Debugger Contributors",
    description="Interactive debugger for PyKokkos workunits",
    long_description="Interactive debugger for PyKokkos kernels with Python front-end and on-device execution.",
    long_description_content_type="text/plain",
    packages=[
        "pkdb",
        "pkdb.runtime",
        "pkdb.core",
        "pkdb.analyzers",
        "pkdb.commands",
        "pkdb.controllers",
        "pkdb.translators",
    ],
    package_dir={"pkdb": "."},
    python_requires=">=3.11",
    install_requires=["pygdbmi>=0.11.0.0"],
    entry_points={
        "console_scripts": [
            "pkdb=pkdb.runtime.main:main",
            "pykokkos-debug=pkdb.runtime.main:main",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Debuggers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
    ],
)
